---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-service
spec:
  type: NodePort
  selector:
    app: master
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100
---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-discovery
spec:
  selector:
    app: master
  ports:
    - protocol: TCP
      port: 50000
      targetPort: 50000
